<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>DvMod.HeadsUpDisplay</RootNamespace>
    <InformationalVersion>1.1.0</InformationalVersion>
    <LangVersion>8.0</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="QuantitiesNet\**" />
    <EmbeddedResource Remove="QuantitiesNet\**" />
    <None Remove="QuantitiesNet\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.0" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="QuantitiesNet\QuantitiesNet\QuantitiesNet.csproj">
      <Private>False</Private>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>Q:\SteamLibrary\steamapps\common\Derail Valley\DerailValley_Data\Managed\Assembly-CSharp.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>Q:\SteamLibrary\steamapps\common\Derail Valley\DerailValley_Data\Managed\UnityModManager\0Harmony.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="CommandTerminal">
      <HintPath>Q:\SteamLibrary\steamapps\common\Derail Valley\DerailValley_Data\Managed\CommandTerminal.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="DV.BrakeSystem">
      <HintPath>Q:\SteamLibrary\steamapps\common\Derail Valley\DerailValley_Data\Managed\DV.BrakeSystem.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="DV.PointSet">
      <HintPath>Q:\SteamLibrary\steamapps\common\Derail Valley\DerailValley_Data\Managed\DV.PointSet.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="DV.RailTrack">
      <HintPath>Q:\SteamLibrary\steamapps\common\Derail Valley\DerailValley_Data\Managed\DV.RailTrack.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="DV.SignPlacer">
      <HintPath>Q:\SteamLibrary\steamapps\common\Derail Valley\DerailValley_Data\Managed\DV.SignPlacer.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="DV.ThingTypes">
      <HintPath>Q:\SteamLibrary\steamapps\common\Derail Valley\DerailValley_Data\Managed\DV.ThingTypes.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="DV.Utils">
      <HintPath>Q:\SteamLibrary\steamapps\common\Derail Valley\DerailValley_Data\Managed\DV.Utils.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>Q:\SteamLibrary\steamapps\common\Derail Valley\DerailValley_Data\Managed\UnityEngine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>Q:\SteamLibrary\steamapps\common\Derail Valley\DerailValley_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>Q:\SteamLibrary\steamapps\common\Derail Valley\DerailValley_Data\Managed\UnityEngine.IMGUIModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>Q:\SteamLibrary\steamapps\common\Derail Valley\DerailValley_Data\Managed\UnityEngine.PhysicsModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>Q:\SteamLibrary\steamapps\common\Derail Valley\DerailValley_Data\Managed\UnityEngine.TextRenderingModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityModManager">
      <HintPath>Q:\SteamLibrary\steamapps\common\Derail Valley\DerailValley_Data\Managed\UnityModManager\UnityModManager.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="net.smkd.vector3d">
      <HintPath>Q:\SteamLibrary\steamapps\common\Derail Valley\DerailValley_Data\Managed\net.smkd.vector3d.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="WorldStreamer">
      <HintPath>Q:\SteamLibrary\steamapps\common\Derail Valley\DerailValley_Data\Managed\WorldStreamer.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="copy $(TargetPath) &quot;Q:\SteamLibrary\steamapps\common\Derail Valley\Mods\cxHeadsUpDisplay\&quot;" />
  </Target>
</Project>
